name: 'Deploy polar code'
description: 'Deploys polar code in the current repository to Oso Cloud'
author: 'Oso'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

runs:
  using: node20
  main: dist/index.js
